name: PowerShell tip submission
description: Submit a new PowerShell tip to be included in the tiPS module
title: "New Tip Submission - Ignore this field and fill in the ones below"
labels: ["automation-new-tip-issue-do-not-use"]
body:
  # NOTE: The input label, required validation, and order is used by the process-new-powershell-tip-issue.yml workflow to extract the data from the issue body.
  # DO NOT change the labels or required validation or ordering without also changing the regex parsing logic of that file.
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to tiPS! Fill out the fields below to submit a new PowerShell tip.

  - type: input
    id: title
    attributes:
      label: Tip Title
      description: A concise title for your tip (max 75 characters)
      placeholder: e.g. Use `-Filter` with `Get-ChildItem` to speed up file searches
    validations:
      required: true

  - type: textarea
    id: tipText
    attributes:
      label: Tip Text
      description: Detailed explanation of the tip. Try to be clear and concise.
      placeholder: Write your tip description here...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code (optional)
      description: Provide one or more PowerShell examples that demonstrates your tip.
      render: powershell
      placeholder: Provide example code here...

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category that best fits your tip.
      options:
        - Community
        - Editor
        - Module
        - NativeCmdlet
        - Performance
        - Security
        - Syntax
        - Terminal
        - Other
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        #### Category descriptions:
        Community: Social events and community resources. e.g. PowerShell Summit, podcasts, etc.
        Editor: Editor tips and extensions. e.g. VS Code, ISE, etc.
        Module: Modules and module tips. e.g. PSScriptAnalyzer, Pester, etc.
        NativeCmdlet: Native cmdlet tips. e.g. Get-Process, Get-ChildItem, Get-Content, etc.
        Performance: Tips to improve runtime performance. e.g. foreach vs ForEach-Object, ForEach-Object -Parallel, etc.
        Security: Security tips. e.g. ExecutionPolicy, Constrained Language Mode, passwords, etc.
        Syntax: Syntax tips. e.g. splatting, pipeline, keywords, etc.
        Terminal: Terminal shortcuts and tips. e.g. PSReadLine, Windows Terminal, ConEmu, etc.
        Other: Tips that don't fit into any of the other categories.

  - type: input
    id: url1
    attributes:
      label: URL 1 (optional)
      description: URL with additional information or examples.
      placeholder: https://LearnMoreHere.com

  - type: input
    id: url2
    attributes:
      label: URL 2 (optional)
      description: URL with additional information or examples.
      placeholder: https://AndSeeOtherExamplesHere.com

  - type: input
    id: url3
    attributes:
      label: URL 3 (optional)
      description: URL with additional information or examples.
      placeholder: https://OfficialDocs.com/OrBlogPost/OrSocialMediaPost

  - type: input
    id: author
    attributes:
      label: Author (optional)
      description: Your name and/or username. Leave blank if you prefer to remain anonymous.
      placeholder: e.g. Daniel Schroeder (deadlydog)

  - type: input
    id: expiryDate
    attributes:
      label: Expiry Date (optional)
      description: Date when the tip should expire and no longer be shown (format of YYYY-MM-DD). Mostly applicable when promoting a community event on a specific date. Leave blank for no expiry.
      placeholder: '2025-10-25'

  - type: input
    id: gitHubCoAuthor
    attributes:
      label: Git Display Name and GitHub Email (optional)
      description: >
        Your display name and GitHub email address. Must be in the GitHub co-author commit format: DisplayName \<EmailAddress\>. e.g. Daniel Schroeder \<deadlydog@hotmail.com\>. This allows you to get attribution in the git history and GitHub. If you do not want to use your public GitHub email address, you can use your private GitHub email address, which can be enabled and found at https://github.com/settings/emails. Leave blank if you prefer to remain anonymous in the git history.
      placeholder: e.g. Daniel Schroeder <deadlydog@hotmail.com>

  - type: markdown
    attributes:
      value: |
        #### By submitting this tip, you agree to make it available under the project's license (MIT).
